name = "LandscapeMetrics"
uuid = "25862bd7-db54-4647-9101-56547424702b"
version = "0.0.1"
authors = ["Timoth√©e Poisot <timothee.poisot@umontreal.ca>"]

[deps]
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"

[compat]
ColorSchemes = "3.31.0"
DelimitedFiles = "1.9"
StatsBase = "0.34"
Test = "1"
TestItems = "1"
